lms/curriculum/urls.py
from django.urls import path,include
from . import views

app_name='curriculum'
urlpatterns = [
    path('', views.StandardListView.as_view(), name='standard_list'),
    path('<slug:slug>/', views.SubjectListView.as_view(), name='subject_list'),
    path('<str:standard>/<slug:slug>/', views.LessonListView.as_view(), name='lesson_list'),
    path('<str:standard>/<str:subject>/<slug:slug>/', views.LessonDetailView.as_view(),name='lesson_detail'),
    path('<str:standard>/<str:slug>/create/', views.LessonCreateView.as_view(),name='lesson_create'),
    path('<str:standard>/<str:subject>/<slug:slug>/update/', views.LessonUpdateView.as_view(),name='lesson_update'),
    path('<str:standard>/<str:subject>/<slug:slug>/delete/', views.LessonDeleteView.as_view(),name='lesson_delete')
]

lms/lms/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('users.urls', 'users'), namespace='users')),
    path('curriculum/', include(('curriculum.urls','curriculum'), namespace='curriculum'))
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lms/users/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('contact/', views.contact, name="contact"),
    path('student/', views.StudentSignUpView.as_view(), name="user_student"),
    path('parent/', views.ParentSignUpView.as_view(), name="user_parent"),
    path('teacher/', views.TeacherSignUpView.as_view(), name="user_teacher"),
    path('principal/', views.PrincipalSignUpView.as_view(), name="user_principal"),
    path('school/', views.SchoolSignUpView.as_view(), name="user_school"),
    path('login/',views.user_login, name="login"),
    path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.register, name='register'),
    path('student_report/',views.studentreport, name="student_report")
]

lms/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    is_student= models.BooleanField(default=False)
    is_parent= models.BooleanField(default=False)
    is_teacher= models.BooleanField(default=False)
    is_principal= models.BooleanField(default=False)
    is_school= models.BooleanField(default=False)

class user_profile_student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True,default="")
    first_name=models.CharField(max_length=50)
    middle_name=models.CharField(max_length=50)
    last_name=models.CharField(max_length=50)
    grade=models.CharField(max_length=50)
    school=models.CharField(max_length=200,default="")
    country=models.CharField(max_length=100)
    state=models.CharField(max_length=50)
    city=models.CharField(max_length=50)

    def __str__(self):
        return self.user.username

class user_profile_parent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True,default="")
    first_name=models.CharField(max_length=50)
    middle_name=models.CharField(max_length=50)
    last_name=models.CharField(max_length=50)
    mobile=models.CharField(max_length=15)

    def __str__(self):
        return self.user.username

class user_profile_teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True,default="")
    first_name=models.CharField(max_length=50)
    middle_name=models.CharField(max_length=50)
    last_name=models.CharField(max_length=50)
    mobile=models.CharField(max_length=15)
    grade=models.IntegerField(null=True)
    school=models.CharField(max_length=200,default="")

    def __str__(self):
        return self.user.username

class user_profile_principal(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True,default="")
    first_name=models.CharField(max_length=50)
    middle_name=models.CharField(max_length=50)
    last_name=models.CharField(max_length=50)
    mobile=models.CharField(max_length=15)
    school=models.CharField(max_length=200,default="")

    def __str__(self):
        return self.user.username

class user_profile_school(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True,default="")
    school_name=models.CharField(max_length=50,default="")
    phone=models.CharField(max_length=50,default="")
    mobile=models.CharField(max_length=15,default="")
    country=models.CharField(max_length=100,default="")
    state=models.CharField(max_length=50,default="")
    city=models.CharField(max_length=50,default="")
    street=models.CharField(max_length=100,default="")
    pin=models.CharField(max_length=50,default="")

    def __str__(self):
        return self.user.username

class Contact(models.Model):
    name=models.CharField(max_length=50)
    contact_no=models.CharField(max_length=15)
    mail=models.EmailField(max_length=50)
    message=models.CharField(max_length=500)

    def __str__(self):
        return self.name

lms/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from users.models import user_profile_student,user_profile_parent,user_profile_principal,user_profile_school,user_profile_teacher,User

class studentsignupform(UserCreationForm):
    email=forms.EmailField(required=True)
    First_Name=forms.CharField(required=True)
    Middle_Name=forms.CharField(required=False)
    Last_Name=forms.CharField(required=True)
    # dob=forms.DateField(required=False)
    grade=forms.CharField(required=True)
    school=forms.CharField(required=True)
    country=forms.CharField(required=False)
    state=forms.CharField(required=False)
    city=forms.CharField(required=False)

    class Meta(UserCreationForm.Meta):
        model=User

    def __init__(self, *args, **kwargs):
        super(studentsignupform, self).__init__(*args, **kwargs)
        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None
        self.fields['username'].help_text = None
        self.label_suffix = ""

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.email=self.cleaned_data.get('email')
        user.is_student = True
        user.save()
        student = user_profile_student.objects.create(user=user)
        student.first_name=self.cleaned_data.get('First_Name')
        student.middle_name=self.cleaned_data.get('Middle_Name')
        student.last_name=self.cleaned_data.get('Last_Name')
        # student.dob=self.cleaned_data.get('dob')
        student.grade=self.cleaned_data.get('grade')
        student.school=self.cleaned_data.get('school')
        student.country=self.cleaned_data.get('country')
        student.state=self.cleaned_data.get('state')
        student.city=self.cleaned_data.get('city')

        # if len('password1') < 8:
        #     self._errors['password'] = self.error_class(['Password length should not be less than 8 characters'])
        student.save()
        return user

class parentsignupform(UserCreationForm):
    email=forms.EmailField(required=True)
    First_name=forms.CharField(required=True)
    Middle_name=forms.CharField(required=False)
    Last_name=forms.CharField(required=True)
    mobile=forms.CharField(required=True)

    class Meta(UserCreationForm.Meta):
        model=User

    def __init__(self, *args, **kwargs):
        super(parentsignupform, self).__init__(*args, **kwargs)
        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None
        self.fields['username'].help_text = None
        self.label_suffix = ""

    @transaction.atomic
    def save(self):
        user=super().save(commit=False)
        user.email=self.cleaned_data.get('email')
        user.is_parent=True
        user.save()
        parent=user_profile_parent.objects.create(user=user)
        parent.first_name=self.cleaned_data.get('First_name')
        parent.middle_name=self.cleaned_data.get('Middle_name')
        parent.last_name=self.cleaned_data.get('Last_name')
        parent.mobile=self.cleaned_data.get('mobile')
        parent.save()

        return parent

class teachersignupform(UserCreationForm):
    email=forms.EmailField(required=True)
    First_Name=forms.CharField(required=True)
    Middle_Name=forms.CharField(required=False)
    Last_Name=forms.CharField(required=True)
    mobile=forms.CharField(required=True)
    # dob=forms.DateField(required=True)
    grade=forms.CharField(required=False)
    school=forms.CharField(required=True)

    class Meta(UserCreationForm.Meta):
        model=User

    def __init__(self, *args, **kwargs):
        super(teachersignupform, self).__init__(*args, **kwargs)
        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None
        self.fields['username'].help_text = None
        self.label_suffix = ""

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.email=self.cleaned_data.get('email')
        user.is_teacher = True
        user.save()
        teacher = user_profile_teacher.objects.create(user=user)
        teacher.first_name=self.cleaned_data.get('First_Name')
        teacher.middle_name=self.cleaned_data.get('Middle_Name')
        teacher.last_name=self.cleaned_data.get('Last_Name')
        teacher.mobile=self.cleaned_data.get('mobile')
        # teacher.dob=self.cleaned_data.get('dob')
        teacher.grade=self.cleaned_data.get('grade')
        teacher.school=self.cleaned_data.get('school')
        teacher.save()
        return teacher

class principalsignupform(UserCreationForm):
    email=forms.EmailField(required=True)
    First_Name=forms.CharField(required=True)
    Middle_Name=forms.CharField(required=False)
    Last_Name=forms.CharField(required=True)
    mobile=forms.CharField(required=True)
    school=forms.CharField(required=True)

    class Meta(UserCreationForm.Meta):
        model=User

    def __init__(self, *args, **kwargs):
        super(principalsignupform, self).__init__(*args, **kwargs)
        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None
        self.fields['username'].help_text = None
        self.label_suffix = ""

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.email=self.cleaned_data.get('email')
        user.is_principal = True
        user.save()
        principal = user_profile_principal.objects.create(user=user)
        principal.first_name=self.cleaned_data.get('First_Name')
        principal.middle_name=self.cleaned_data.get('Middle_Name')
        principal.last_name=self.cleaned_data.get('Last_Name')
        principal.mobile=self.cleaned_data.get('mobile')
        principal.school=self.cleaned_data.get('school')
        principal.save()
        return principal

class schoolsignupform(UserCreationForm):
    email=forms.EmailField(required=True)
    School_Name=forms.CharField(required=True)
    phone=forms.CharField(required=True)
    mobile=forms.CharField(required=True)
    # established=forms.DateField(required=False)
    country=forms.CharField(required=True)
    state=forms.CharField(required=True)
    city=forms.CharField(required=True)
    street=forms.CharField(required=False)
    pin=forms.CharField(required=False)

    class Meta(UserCreationForm.Meta):
        model=User

    def __init__(self, *args, **kwargs):
        super(schoolsignupform, self).__init__(*args, **kwargs)
        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None
        self.fields['username'].help_text = None
        self.label_suffix = ""

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.email=self.cleaned_data.get('email')
        user.is_school = True
        user.save()
        school = user_profile_school.objects.create(user=user)
        school.school_name=self.cleaned_data.get('School_Name')
        school.phone=self.cleaned_data.get('phone')
        school.mobile=self.cleaned_data.get('mobile')
        # school.established=self.cleaned_data.get('established')
        school.country=self.cleaned_data.get('country')
        school.state=self.cleaned_data.get('state')
        school.city=self.cleaned_data.get('city')
        school.street=self.cleaned_data.get('street')
        school.pin=self.cleaned_data.get('pin')
        school.save()
        return school

class LoginForm(forms.Form):
    username = forms.CharField(
        widget= forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )

lms/users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,logout,login
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from users.models import Contact,User
from users.forms import studentsignupform,parentsignupform,teachersignupform,principalsignupform,schoolsignupform
from django.views.generic import CreateView
from django.contrib import messages

# Create your views here.
def index(request):
    return render(request,"users/index.html")

class StudentSignUpView(CreateView):
    model = User
    form_class = studentsignupform
    template_name = 'users/student.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        return redirect('users:index')

class ParentSignUpView(CreateView):
    model = User
    form_class = parentsignupform
    template_name = 'users/parent.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'parent'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        return redirect('users:index')

class TeacherSignUpView(CreateView):
    model = User
    form_class = teachersignupform
    template_name = 'users/teacher.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'teacher'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        return redirect('users:index')

class PrincipalSignUpView(CreateView):
    model = User
    form_class = principalsignupform
    template_name = 'users/principal.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'principal'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        return redirect('users:index')

class SchoolSignUpView(CreateView):
    model = User
    form_class = schoolsignupform
    template_name = 'users/school.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'school'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        return redirect('users:index')

def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request,username=username, password=password)
        if user is not None:
            login(request,user)
            messages.success(request, "You have successfully logged in.")
            return render (request,'users/login.html')
        else:
            return HttpResponse("Please use correct id and password")

    else:
        return render(request, 'users/login.html')

@login_required
def user_logout(request):
    logout(request)
    messages.success(request,"You have successfully logout")
    return render(request, 'users/index.html')

def register(request):
    return render(request, 'users/register.html')

def contact(request):
    if request.method=="POST":
        name=request.POST.get('name')
        contact_num=request.POST.get('contact')
        email=request.POST.get('email')
        message=request.POST.get('message')

        con=Contact(name=name, contact_no=contact_num, mail=email, message=message)
        con.save()
    return render(request, "users/contact.html")   

def studentreport(request):
    return render(request, "users/student_report.html")

lms/templates/users/contact.html
{% extends 'base.html' %}

{% load static %}
{% block title %}Contact Us{% endblock %}
{% block body %}
<section id="contact-body">
    <div class="contact-form">
        <img alt="" class="avatar" src="/static/Images/user_avatar.png">
        <h2>Contact Us</h2>
        <form action="{% url 'users:contact' %}" method="post">
        {% csrf_token %}
            <p>Name</p><input placeholder="Enter your name" id="name" name="name" type="text">
            <p>Contact number</p><input placeholder="Enter your contact number" id="contact" name="contact" type="tel">
            <p>Email</p><input placeholder="Enter your email" id="email" type="email" name="email">
            <p>Your Message</p><input placeholder="Leave your message" id="message" type="text" name="message">
            <input type="submit" value="Submit">
        </form>
    </div>
</section>
{% endblock %}

lms/templates/users/index.html
{% extends 'base.html' %}
{% load static %}

{% block image_block%}
<header>
    <!--Image and mask-->
    <div id="intro" class="container-fluid d-flex align-items-center
        justify-content-center h-100 my-2">
        <div class="row d-flex justify-content-center text-center">
            <div class="col-md-10 text-white">
                <!-- heading -->
                <h4 class="display-4 font-weight-bold white-text mb-2">Start
                    Learning- <span class="auto-input" style="color:#ff5722;"></span></h4>
                <!-- divider -->
                <hr style="color:white;">

                <!-- description -->
                <h4 class="text-white my-4">ABL Education leverages its
                    intelligently curated technology tools & learning
                    resources to foster 21st-century skills.</h4>
                <a href="{% url 'curriculum:standard_list' %}"> <button
                        type="button" class="btn"
                        style="color:white;border-color:white;"> Start Now</button>
                </a>

                <!-- feedback and github -->
                <div class="row d-flex mt-5 justify-content-center text-center">
                    <div class="col">
                        <a href="contact/"> <button type="button" class="btn"
                                style="color:white;border-color:white;">Send
                                Feedback</button> </a>
                    </div>
                    <div class="col">
                        <a href="http://www.ableducation.com/" target="_blank">
                            <button
                                type="button" class="btn"
                                style="color:white;border-color:white;"> Get on
                                website</button> </a>
                    </div>
                    <div class="col">
                        <a href="https://www.youtube.com/@ABLEducation"
                            target="_blank"> <button
                                type="button" class="btn"
                                style="color:white;border-color:white;">
                                Subscribe on Youtube</button> </a>
                    </div>
                </div>

            </div>
        </div>
    </div>

</header>
{%endblock%}

{% block body %}
<section id="carousel">
    <div class="carousel">
        <div id="carouselExampleControls" class="carousel slide"
            data-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="/static/Images/c1.jpg" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="/static/Images/c2.jpg" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="/static/Images/c3.jpg" class="d-block w-100"
                        alt="...">
                </div>
                <div class="carousel-item">
                    <img src="/static/Images/1.jpg" class="d-block w-100"
                        alt="...">
                </div>
            </div>
            <button class="carousel-control-prev" type="button"
                data-bs-target="#carouselExampleControls"
                data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button"
                data-bs-target="#carouselExampleControls"
                data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
</carousel>

<section id="user_profile">
    <div class="container my-2">
        <div class="text-center my-2">
            <h1 class="text-success">One Platform for all</h1>
        </div>
        <div class="row">
            <div class="col col-lg-4">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Parent</h5>
                        <p class="card-text">Some quick example text to build on
                            the card title and make up the bulk
                            of the card's content.</p>
                        <a href="{% url 'users:student_report' %}" class="btn btn-success">Get Reports</a>
                    </div>
                </div>
            </div>
            <div class="col col-md-4">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Student</h5>
                        <p class="card-text">Some quick example text to build on
                            the card title and make up the bulk
                            of the card's content.</p>
                        <a href="{% url 'curriculum:standard_list' %}"
                            class="btn btn-success" ">Start Learning</a>
                    </div>
                </div>
            </div>
            <div class=" col col-md-4">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Teacher</h5>
                        <p class="card-text">Some quick example text to build on
                            the card title and make
                            up the bulk of the card's content.</p>
                        <a href="#" class="btn btn-success" ">Get Updates</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% comment %} <section class="testimonials">
    <div class="container">
        <h2 class="text-center my-2 text-white">What Our User Say</h2>
        <div class="row">
            <div class="col-lg-4">
                <div class="card">
                    <div class="face front-face">
                        <img
                            src="https://images.unsplash.com/photo-1557862921-37829c790f19?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1051&q=80"
                            alt="" class="profile">
                        <div class="pt-3 text-uppercase name">
                            Robert Garrison
                        </div>
                        <div class="designation">Android Developer</div>
                    </div>
                    <div class="face back-face">
                        <span class="fas fa-quote-left"></span>
                        <div class="testimonial">
                            I made bacck the purchase price in just 48 hours!
                            Thank you for making it pain less,
                            pleasant.
                            The service was execellent. I will refer everyone I
                            know.
                        </div>
                        <span class="fas fa-quote-right"></span>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="card">
                    <div class="face front-face">
                        <img
                            src="https://images.unsplash.com/photo-1600486913747-55e5470d6f40?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80"
                            alt="" class="profile">
                        <div class="pt-3 text-uppercase name">
                            Jeffery Kennan
                        </div>
                        <div class="designation">Full Stack Developer</div>
                    </div>
                    <div class="face back-face">
                        <span class="fas fa-quote-left"></span>
                        <div class="testimonial">
                            Really good, you have saved our business! I made
                            bacck the purchase price in just 48 hours!
                            man, this thing is getting better and better as I
                            learn more about it.
                        </div>
                        <span class="fas fa-quote-right"></span>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="card">
                    <div class="face front-face">
                        <img
                            src="https://images.unsplash.com/photo-1614574762522-6ac2fbba2208?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjY2fHxtYW58ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60"
                            alt="" class="profile">
                        <div class="pt-3 text-uppercase name">
                            Issac Maxwell
                        </div>
                        <div class="designation">Finance Director</div>
                    </div>
                    <div class="face back-face">
                        <span class="fas fa-quote-left"></span>
                        <div class="testimonial">
                            Account keeper is the most valuable business
                            research we have EVER purchased. Without
                            electrician, we would ahave gone bankrupt by now.
                        </div>
                        <span class="fas fa-quote-right"></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section> {% endcomment %}

<section id="footer">
    <div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Services</h3>
                        <ul>
                            <li><a href="#">Home</a></li>
                            <li><a href="#">Curriculum</a></li>
                            <li><a href="#">Blog</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>About</h3>
                        <ul>
                            <li><a href="#">Company</a></li>
                            <li><a href="#">Team</a></li>
                            <li><a href="#">Careers</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-6">
                        <div class="footer-top-menu">
                            <h3 class="widget-title">Schools</h3>
                            <div class="fo-course-container">
                                <ul>
                                    <li><a href="http://www.ableducation.com/" target="_blank">STEM Lab</a></li>
                                    <li><a href="http://www.ableducation.com/"target="_blank">RoboShala</a></li>
                                    <li><a href="http://www.ableducation.com/"target="_blank">STEM Club</a></li>
                                    <li><a href="http://www.ableducation.com/"target="_blank">RoboShiksha</a></li>
                                    <li><a href="/steam-olympiad-2022/"
                                            target="_blank">STEAM Olympiad</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-6">
                        <div class="footer-top-menu">
                            <h3 class="widget-title">CONTACT US</h3>
                            <div class="fo-aboutus-container">
                                <address>
                                    <p><strong>Address:</strong> G-233, Ground
                                        Floor, Sector 63, Noida - 201301,<br>Uttar
                                        Pradesh</p>
                                    <p><strong>Email: </strong><a
                                            href="mailto:sales@thinnkware.com">care@ableducation.com</a></p>
                                    <p><strong>Phone: </strong>+91-120-4541854,
                                        9211786061</p>
                                </address>
                            </div>
                        </div>
                    </footer>
                </div>
            </section>
            {% endblock %}

            {% block js %}
            <script>
    var type=new Typed(".auto-input",{
        strings:["Coding", "Robotics", "Artificial Intelligence","Science","Machine Learning"],
        typeSpeed:100,
        backSpeed:100,
        loop:true
    } )
</script>
            {% endblock %}

lms/templates/users/login.html
{% extends 'base.html' %}

{% load static %}
{% block title %}Login Form{% endblock %}
{% block body %}

<section id="login">
    <div class="login-form">
        <img alt="" class="avatar" src="/static/Images/user_avatar.png">
        <h2>Login</h2>
        <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
            <p>Username</p><input name="username" placeholder="Enter your email" type="text">
            <p>Password</p><input name="password" placeholder="Enter your password" type="password">
            <input type="submit" value="Login">
            <div class="text-center my-2">
                <p>Don't have an account yet?</p>
                <h6><a href="{% url 'users:register' %}">Register Here</a></h6>
            </div>
        </form>
    </div>
</section>
{% endblock %}